name: Update status

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./scripts

    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1

      - name: Install dependencies
        run: dart pub get

      - name: Hello world
        run: dart ci.dart

      - uses: EndBug/add-and-commit@v7
        with:
          add: './software/recedar/'
          message: Update status of reCedar project
          committer_name: GitHub Actions
          committer_email: actions@github.com